config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
      get 'users/sign_out' => "devise/sessions#destroy"
  end

  scope "(:locale)", locale: /en|es|pt/  do
    get 'home/index'
    root 'pages#home'
    resources :memoirs
    resources :resources
    get 'pages/join'
    get 'pages/about'
    get 'pages/home'
    get 'pages/laboratorio'
    get '/labmemorias', to: redirect('pages/laboratorio')
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Memoir, public: true

    if user.present?
      can [:read, :create], Memoir
      can [:update, :destroy], Memoir, :user_id => user.id
      if user.has_role? :admin
        can :manage, :all
        can :dashboard, :all
        can :access, :rails_admin
      elsif user.has_role? :editor
        can :manage, :all
        can :dashboard, :all
        can :access, :rails_admin
      end
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  translates :name
  accepts_nested_attributes_for :translations, allow_destroy: true

  # validates :latitude, presence: true
  # validates :longitude, presence: true
  #
  has_many :memoirs

  geocoded_by :name
  # can be used to retrieve coordinates based on the provided address
  # after_validation :geocode, if: ->(obj){ obj.name.present? and obj.name_changed? }
  after_validation :geocode, if: ->(obj){ obj.name.present? and obj.name_changed? }

end

app/models/audio.rb
class Audio < ApplicationRecord
  belongs_to :memoir

end

app/models/member.rb
class Member < ApplicationRecord
  has_one_attached :logo

end

app/models/memoir.rb
class Memoir < ApplicationRecord
  translates :title, :description, :summary, :report
  accepts_nested_attributes_for :translations, allow_destroy: true

  has_rich_text :post

  has_one_attached :image
  has_many_attached :gallery

  belongs_to :area

  belongs_to :user

  has_many :resources
  accepts_nested_attributes_for :resources

  has_many :audios
  accepts_nested_attributes_for :audios

  has_many :quotes
  accepts_nested_attributes_for :quotes

end

app/models/quote.rb
class Quote < ApplicationRecord
  translates :who, :content
  accepts_nested_attributes_for :translations, allow_destroy: true

  has_one_attached :avatar
  belongs_to :memoir


end

app/models/resource.rb
class Resource < ApplicationRecord
  translates :title, :description
  accepts_nested_attributes_for :translations, allow_destroy: true

  has_one_attached :attach
  belongs_to :memoir

end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles

belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  has_many :memoirs

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def name
    self.email
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, alert: exception.message
  end

  def default_url_options
    { locale: I18n.locale }
  end
  
  private
    def set_locale
      I18n.locale = extract_locale || I18n.default_locale
    end

    def extract_locale
      parsed_locale = params[:locale] || request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/)[0] if request.env['HTTP_ACCEPT_LANGUAGE']
      I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
    end


end

app/controllers/memoirs_controller.rb
class MemoirsController < ApplicationController
  before_action :set_memoir, only: [:show, :edit, :update, :destroy]

  def index
    @memoirs = Memoir.all
  end

  def show
    @memoir = Memoir.find(params[:id])
  end

  # GET /memoirs/new
  def new
    @memoir = Memoir.new
    @memoir.build_area
  end

  # GET /memoirs/1/edit
  def edit
  end

  # POST /memoirs
  def create
    @memoir = Memoir.new(memoir_params)
    if @memoir.save
      redirect_to memoir_path(@memoir), notice: 'Memoir was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /memoirs/1
  def update
    if @memoir.update(memoir_params)
      redirect_to memoir_path(@memoir), notice: 'Memoir was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /memoirs/1
  def destroy
    @memoir.destroy
    redirect_to memoirs_url, notice: 'Memoir was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memoir
      @memoir = Memoir.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def memoir_params
      params.require(:memoir).permit(:title, :image, :user_id, :summary, :description, :post, :vimeo_link, :youtube_link, area_attributes: [:latitude, :longitude, :name])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def context
  end

  def join
  end

  def home
    @last_memoirs = Memoir.order(created_at: :desc).first(5)
  end

  def about
  end

  def Laboratorio
  end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  def index
    @resources = Resource.all
  end

  def new
  end

  def edit
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    markdown.render(text).html_safe
  end

end

app/helpers/memoir_helper.rb
module MemoirHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memoria Ambiental por el Futuro</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Animate -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">

    <!-- Hover -->
    <link href="css/hover-min.css" rel="stylesheet">

    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/css/uikit.min.css" />

    <!-- UIkit JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/js/uikit-icons.min.js"></script>
    <script src="uikit/dist/js/uikit-icons.min.js"></script>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Muli:400,600,700,800|Work+Sans:400,600,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&display=swap" rel="stylesheet">

    <!-- Mapbox -->
    <script src='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.css' rel='stylesheet' />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <%= render 'shared/navbar' %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/memoirs/_area_fields.html.erb
<div class='nested-fields'>

  <div class="uk-margin">
    <%= f.label :name, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <%= f.text_field :name, class: 'uk-input' %>
    </div>
  </div>

</div>

app/views/memoirs/_form.html.erb
<%= simple_form_for memoir, html: { class: 'uk-form-horizontal uk-margin-large'} do |f| %>

  <% if memoir.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(memoir.errors.count, "error") %> prohibited this actor category from being saved:</h2>
      <ul>
        <% memoir.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.association :user, as: :hidden, class: 'uk-input', input_html: {name: 'memoir[user_id]', value: current_user.id } %>

  <div class="uk-margin">
    <%= f.label :title, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <%= f.input_field :title, class: 'uk-input' %>
    </div>
  </div>

  <div class="uk-margin">
    <%= f.label :summary, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <%= f.input_field :summary, class: 'uk-input' %>
    </div>
  </div>

  <div class="uk-margin">
    <%= f.label :area, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <%= f.simple_fields_for :area do |area| %>
        <%= area.text_field :name, class: 'uk-input' %>
      <% end %>
    </div>
  </div>

  <div class="uk-margin">
    <%= f.label :image, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <% if @memoir.image.attached? %>
        <label class="uk-button uk-button-default ">
          Subir desde tu computador
          <span style="display:none;">
            <%= f.input_field :image, as: :file %>
          </span>
        </label>
        <br>
        Icono actual: <img src="<%= url_for(@memoir.image) %>" width="40" height="40" uk-svg>
      <% else %>
        <label class="uk-button uk-button-primary">
          Subir desde tu computador
          <span style="display:none;">
            <%= f.input_field :image, as: :file %>
          </span>
        </label>
      <% end %>
    </div>
  </div>

  <div class="uk-margin">
    <%= f.label :description, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <%= f.input_field :description, class: 'uk-input' %>
    </div>
  </div>


  <div class="uk-margin">
    <%= f.label :post, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <%= f.rich_text_area :post, class: 'uk-input' %>
    </div>
  </div>

  <div class="uk-margin">
    <%= f.label :vimeo_link, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <%= f.input_field :vimeo_link, class: 'uk-input' %>
    </div>
  </div>

  <div class="uk-margin">
    <%= f.label :youtube_link, class: 'uk-form-label uk-margin-remove' %>
    <div class="uk-form-controls">
      <%= f.input_field :youtube_link, class: 'uk-input' %>
    </div>
  </div>

  <div class="uk-margin">
    <div class="uk-form-controls">
      <%= f.button :submit, class: 'uk-button button-color-purple' %>
    </div>
  </div>

<% end %>


<%#
t.string "title"
t.text "description"
t.text "summary"
t.datetime "created_at", precision: 6, null: false
t.datetime "updated_at", precision: 6, null: false
t.bigint "area_id"
t.text "report"
t.string "vimeo_link"
t.string "youtube_link" %>

app/views/memoirs/edit.html.erb
<ul class="uk-breadcrumb">
  <li> <%= link_to 'Memorias', memoirs_path %> </li>
  <li><span><%= @memoir.title %></span></li>
</ul>

<h1>Editar memoria</h1>

<%= render 'form', memoir: @memoir %>

app/views/memoirs/index.html.erb
<div class="uk-inline uk-visible@s">
  <img class="opacity-img" src="<%= asset_path('home/ma_3.jpg') %>" >
  <div class="uk-position-medium uk-position-bottom uk-overlay uk-light">
    <div class="uk-container animated fadeInUp">
      <h2> <%= t('memoirs.title') %>  </h2>
      <h4 class="uk-margin-remove"><%= t('memoirs.description') %> </h4>
    </div>
  </div>
</div>

<div id="list-memoirs" class="uk-container uk-padding-large">
  <div uk-grid="masonry: true">
    <% @memoirs.each_with_index do |memoir, index| %>
      <div class="uk-width-1-3@m">
        <%= link_to memoir_path(memoir) , :class => '' do  %>
          <div class="uk-card uk-card-default">
            <% if memoir.image.attached? %>
              <img src="<%= url_for(memoir.image) %>" alt="">
            <% end %>
            <div class="uk-card-body uk-padding-small">
              <p class="uk-card-title uk-text-lead"><%= memoir.title %></p>
              <p> <span class="uk-margin-small-right" uk-icon="location"></span>
                <%= memoir.area.name %>
              </p>
              <p class="uk-text-muted"> <%= memoir.summary %> </p>
              <%= link_to 'Conocer memoria', memoir_path(memoir) %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>



<%= render 'shared/why' %>

app/views/memoirs/new.html.erb
<div class="uk-inline uk-visible@s">
  <img class="opacity-img" src="<%= asset_path('home/ma_3.jpg') %>" >
  <div class="uk-position-medium uk-position-bottom uk-overlay uk-light">
    <div class="uk-container animated fadeInUp">
      <h2> <%= t('memoirs.title') %>  </h2>
      <h4 class="uk-margin-remove"><%= t('memoirs.description') %> </h4>
    </div>
  </div>
</div>

<div class="uk-container uk-padding">

  <ul class="uk-breadcrumb">
    <li> <%= link_to 'Memoria', memoirs_path %> </li>
    <li><span>Crear memoria</span></li>
  </ul>


  <h2>Nueva memoria</h2>

  <%= render 'form', memoir: @memoir %>

</div>

app/views/pages/about.html.erb
<div class="uk-inline uk-visible@s">
  <img class="opacity-img" src="<%= asset_path('home/ma_2.jpg') %>" >
  <div class="uk-position-medium uk-position-bottom uk-overlay uk-light">
    <div class="uk-container animated fadeInUp">
      <h2> <%= t('about.title') %>  </h2>
      <h4 class="uk-margin-remove"> <%= t('about.description') %></h4>
    </div>
  </div>
</div>

<div class="uk-hidden@m uk-height-medium uk-flex uk-flex-center uk-flex-middle uk-background-cover uk-light" data-src="<%= asset_path('home/ma_2.jpg') %>" uk-img>
  <div class="uk-container uk-text-center">
    <h3 class="uk-text-bold">  <%= t('about.title') %>  </h3>
    <p class="uk-margin-remove white"><%= t('about.description') %></p>
  </div>
</div>

<section id="about-us">
  <div class="uk-container uk-container-small uk-padding-large">
    <p class="uk-h4 uk-text-center">
      <%= t('about.sentence1') %>
    </p>
    <p class="uk-h4 uk-text-center">
      <span class="uk-text-bold">
        <%= t('about.sentence2') %> </span>
    </p>
    <p class="uk-h4 uk-text-center uk-text-break">
      Creemos que las historias tienen poder, <br>
      las memorias del pasado<br>
      producidas en el presente<br>
      pueden transformar el futuro<br>
    </p>
  </div>
</section>

<section id="more-about">
  <div class="uk-section uk-flex-center bg-terracota uk-light">
    <div class="uk-container">
      <div class="uk-column-1-2@m uk-column-divider">
        <h3> <%= t('about.ask1') %> </h3>
        <p class="white">
          <%= t('about.content1') %>
        </p>
        <p class="white">
          <%= t('about.content2') %>
        </p>
        <p class="white">
          <%= t('about.content3') %>
        </p>
      </div>
    </div>
  </div>
</section>


<section id="team">

</section>

app/views/pages/home.html.erb
<div class="uk-visible@s">
  <div class="">
    <img src="<%= asset_path('home/memoria_home.jpg') %>" >
    <div class="uk-position-center">
      <div class="uk-container uk-text-center uk-width-2-3@m">
        <div class="uk-light animated fadeInUp">
          <h1 style="margin-bottom:-20px;"> <%= t('home.title') %> </h1>
          <h3 class="white"><%= t('home.description')%></h3>
          <%= link_to "Conoce más", pages_about_path,
          :class => 'uk-button uk-button-secondary white' %>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="uk-hidden@m uk-height-large uk-flex uk-flex-center uk-flex-middle uk-background-cover uk-light" data-src="<%= asset_path('home/memoria_home.jpg') %>" height="500" uk-img>
  <div class="uk-container uk-text-center">
    <h1 class=""> <%= t('home.title') %> </h1>
    <p class="white"><%= t('home.description')%></p>
    <%= link_to "Conoce más", pages_about_path,
    :class => 'uk-button uk-button-secondary white' %>
  </div>
</div>


<section id="main-memoirs">
  <div class="uk-container uk-padding-large">
    <h2 class="uk-text-center uk-padding-small"> <%= t('memoirs.title') %>  </h2>
    <div uk-slider>
      <div class="uk-position-relative">
        <div class="uk-slider-container">
          <ul class="uk-slider-items uk-child-width-1-1 uk-child-width-1-1@s uk-child-width-1-3@m uk-grid">
            <% @last_memoirs.each_with_index do |memoir, index| %>
              <li class="uk-transition-toggle" tabindex="0">
                <%= link_to memoir_path(memoir) , :class => '' do  %>
                  <div class="uk-card uk-card-default uk-card-hover">
                    <div class="uk-card-media-top">
                      <% if memoir.image.attached? %>
                        <img src="<%= url_for(memoir.image) %>" alt="">
                      <% end %>
                    </div>
                    <div class="uk-card-body uk-padding-small">
                      <p class="uk-card-title uk-text-lead"><%= memoir.title %></p>
                      <p> <span class="uk-margin-small-right" uk-icon="location"></span>
                        <%= memoir.area.name %>
                      </p>
                      <p class="uk-text-muted"> <%= memoir.summary %> </p>
                      <%= link_to 'Conocer memoria', memoir_path(memoir) %>
                    </div>
                  </div>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="uk-hidden@s uk-light">
             <a class="uk-position-center-left uk-position-small" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
             <a class="uk-position-center-right uk-position-small" href="#" uk-slidenav-next uk-slider-item="next"></a>
         </div>

         <div class="uk-visible@s">
             <a class="uk-position-center-left-out uk-position-small" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
             <a class="uk-position-center-right-out uk-position-small" href="#" uk-slidenav-next uk-slider-item="next"></a>
         </div>
      </div>
    </div>
  </div>
</section>



<%= render 'shared/why' %>

app/views/resources/index.html.erb
<h1> Resources </h1>

<% @resources.each do |resource| %>
  <% if resource.image.attached? %>
    <img src="<%= url_for(resource.image) %>" alt="<%= resource.image.filename %>">
  <% end %>
  <h2> <%= resource.title %> </h2>
  <p> <%= resource.description %> </p>
  <% if resource.attach.attached? %>
    <%= link_to 'Descargar', url_for(resource.attach), target: "_blank" %>
  <% end %>
  <br>
<% end %>

app/views/shared/_about.html.erb
<div class="uk-section  uk-flex-center uk-text-center">
    <div class="uk-container uk-container-small">

      <h4 class="subtitle"> <%= t('call_to_action.title') %> </h4>

      <%= link_to memoirs_path , :class => 'uk-button uk-button-primary' do  %>
        <%= t('call_to_action.see_more') %>
      <% end %>
      <%= link_to memoirs_path , :class => 'uk-button uk-button-default' do  %>
        <%= t('call_to_action.document') %>
      <% end %>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-gray-light">
  <div class="uk-grid-match uk-grid-small uk-text-center" uk-grid>
    <div class="uk-width-1-3@m">
      <div class="uk-card uk-card-body">
        <img data-src="<%= asset_path('logo_memoria.png')%>" width="300" alt="Logo Memoria Ambiental" uk-img>
      </div>
    </div>
    <div class="uk-width-1-3@m">
      <div class="uk-card uk-card-body">
        Buscamos mostrar como el cambio climático esta afectando la vida de las personas. <br> <%= link_to 'Conoce las memorias ambientales', memoirs_path %>
      </div>
    </div>
    <div class="uk-width-1-3@m">
      <div class="uk-card uk-card-body">
        <a href="https://instagram.com/memoriaambiental" target="_blank" class="uk-icon-link" uk-icon="instagram"></a>
        <a href="https://twitter.com/MemoriAmbiental" target="_blank" class="uk-icon-link" uk-icon="twitter"></a>
        <a href="https://wa.me/+5521995905064" target="_blank" class="uk-icon-link" uk-icon="whatsapp"></a>
        <h4> contacto@memoriaambiental.org </h4>
      </div>
    </div>
  </div>


  <div class="uk-container uk-container-small uk-text-center uk-padding-small">
    <img data-src="<%= asset_path('ccheart_black.svg')%>" width="24" alt="Logo Memoria Ambiental" uk-img> Este proyecto está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>
  </div>


</footer>

app/views/shared/_navbar.html.erb
<div class="uk-section menu-bar weight-regular uk-visible@s">
  <div class="uk-container">
    <nav class="uk-navbar-transparent uk-flex uk-flex-middle" uk-navbar>
      <div class="uk-navbar-left">
        <ul class="uk-list">
          <li>
            <%= link_to root_path do %>
              <!-- <h2 class="white">MemoriaAmbiental.org</h2> -->
              <img data-src="<%= asset_path('logo_ma.png')%>" width="300" alt="Logo Memoria Ambiental" uk-img>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="uk-navbar-right">
        <ul class="uk-navbar-nav">
          <li class="<%= 'uk-active' if current_page?(pages_join_path) %>"> <%= link_to t('navbar.join'),  pages_join_path , :class => 'navbar-link'  %> </li>
          <li class="<%= 'uk-active' if current_page?(pages_about_path) %>"> <%= link_to t('navbar.about'),  pages_about_path , :class => 'navbar-link'  %> </li>
          <li> <%= link_to t('language_name', locale: :es), request.params.merge(locale: :es), class: 'dropdown-item' %> </li>
          <li> <%= link_to t('language_name', locale: :pt), request.params.merge(locale: :pt), class: 'dropdown-item' %> </li>
          <li class="<%= 'uk-active' if current_page?(memoirs_path) %>"> <%= link_to t("navbar.memoirs"),  memoirs_path , :class => 'navbar-link uk-button uk-button-default green-dark'  %> </li>
          <li class='uk-active'>
            <a href="https://instagram.com/memoriaambiental" target="_blank" class="uk-icon-link uk-icon-white" uk-icon="instagram"></a>
          </li>
          <li class='uk-active'>
            <a href="https://twitter.com/MemoriAmbiental" target="_blank" class="uk-icon-link uk-icon-white" uk-icon="twitter"></a>
          </li>
          <li class='uk-active'>
            <a href="https://wa.me/+5521995905064" target="_blank" class="uk-icon-link uk-icon-white" uk-icon="whatsapp"></a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</div>

<nav class="uk-hidden@s" uk-navbar>
  <div class="uk-navbar-left">
    <%= link_to root_path do %>
      <img data-src="<%= asset_path('logo_memoria.png')%>" width="200" alt="Logo Memoria Ambiental" class="uk-padding-small" uk-img>
    <% end %>

  </div>
  <div class="uk-navbar-right">
    <a class="uk-navbar-toggle" uk-navbar-toggle-icon uk-toggle="target: #offcanvas-flip"></a>
    <div id="offcanvas-flip" uk-offcanvas="flip: true; overlay: true; mode: push">
      <div class="uk-offcanvas-bar">
        <button class="uk-offcanvas-close" type="button" uk-close></button>
        <ul class="uk-list">
          <li class="<%= 'uk-active' if current_page?(root_path) %>"> <%= link_to t('navbar.home'), root_path, :class => 'navbar-link'  %> </li>
          <li class="<%= 'uk-active' if current_page?(memoirs_path) %>"> <%= link_to t("navbar.memoirs"),  memoirs_path , :class => 'navbar-link'  %> </li>
          <li class="<%= 'uk-active' if current_page?(pages_join_path) %>"> <%= link_to t('navbar.join'),  pages_join_path , :class => 'navbar-link'  %> </li>
          <li class="<%= 'uk-active' if current_page?(pages_about_path) %>"> <%= link_to t('navbar.about'),  pages_about_path , :class => 'navbar-link'  %> </li>
          <li class='uk-active'>
            <a href="https://instagram.com/memoriaambiental" target="_blank" class="uk-icon-link" uk-icon="instagram"></a>
            <a href="https://twitter.com/MemoriAmbiental" target="_blank" class="uk-icon-link" uk-icon="twitter"></a>
            <a href="https://wa.me/21995905064" target="_blank" class="uk-icon-link" uk-icon="whatsapp"></a>
          </li>
        </ul>
        <hr class="uk-divider-small">
        <ul class="uk-list">
          <li class="small-text"> <%= link_to t('language_name', locale: :es), request.params.merge(locale: :es), class: 'dropdown-item' %> </li>
          <li class="small-text"> <%= link_to t('language_name', locale: :pt), request.params.merge(locale: :pt), class: 'dropdown-item' %> </li>
        </ul>
      </div>
    </div>
  </div>
</nav>